### ISSUE TITLE
Investigate different implementation for computing an activity code

### ISSUE THREAD

**Issue by meteabduraman** [Denisa-Georgiana-Dulica/Continuous-feedback-application#20]
I see that in order for you to compute this next code, you're doing a database transaction first, do you think we can implement this differently so that a database operation is not needed first? (database operations usually introduce latency, here it won't be necessarily felt because it's a small project, but usually we want to have **the smallest number of potentially latent operations**)

A couple options I can think of that may need some investigation:
- Investigate if **auto-increment** works in your database for fields which are not primary key, and let the database compute the new code upon inserting the activity
- Randomly generate a numeric code in the application without depending on previous rows stored in the database (either by hand, or maybe via an `npm` library)

Take this as an improvement point, if there's time remaining while building your backend, feel free to address this, otherwise, just keep this in mind for the future.

Really nice idea overall 😇

_Originally posted by @meteabduraman in https://github.com/Denisa-Georgiana-Dulica/Continuous-feedback-application/pull/5#discussion_r1869367670_

**Comment by Denisa-Georgiana-Dulica** [comment]
I initially tried to use auto-increment in the database, but I did not succeed. Then I thought of creating a code as unique as possible and I combined a uuid with the milliseconds of the current date and I got a 6 digit code. I hope it's ok like that.

**Comment by meteabduraman** [comment]
Awesome job! Looks really nice 🥳

**Comment by Mihneas22** [comment]
@meteabduraman Salut! Ma numesc Mihnea si am fost la un curs de Javascript pe care l-ai predat in vara la Iasi, la ThinkHub. Personal, am inceput sa lucrez in backend si intampin niste probleme si voiam sa cer un sfat daca esti dispus sa il dai. Daca ai vrea, imi poti da un whatsapp/insta/discord sa vorbim mai multe? Mersi :)

**Comment by meteabduraman** [comment]
@Mihneas22 Salut! M-aș bucura tare să ajut 🥳 Mă găsești pe Discord @meteabduraman
